name: linter_and_test
on: [pull_request]
jobs:
  linter_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
      - name: Test
        run: go test ./...